title: 'TropicYou - Hobby, Pertanian Organic Hydroponic, Kuliner, & Merajut '
email: mail@tropi.cyou
description: Aneka Hobby / Kuliner / Rajutan / Bercocok Tanam Organic & Hidroponik
author: Admin
baseurl: ''
url: ''
date_format: '%d %B %Y'
paginate: 9
paginate_path: '/blog/page:num/'
permalink: pretty
disqus_comments: 'yes'
disqus_shortname: glitche-jekyll-theme
formsubmit_email: mail@tropi.cyou
collections:
  - works
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive
    tag: archive
  permalinks:
    category: '/categories/:name/'
    tag: '/tags/:name/'
plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-admin
  - jekyll-sitemap
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
sass:
  style: compressed
markdown: kramdown
