# Theme Settings Configuration File
##
### use settings.yml file for configure colors, ui, rtl, sidebar, animation options

### Main Settings
settings:
  logo_text: "Tropic <strong>You</strong>"
  logo_hover_text: "Download <strong>CV</strong>"
  quick_colors: "" # select quick color schemes: "beige", "blue", "brown", "green_light", "green", "orange", "purple", "red", "yellow_light", "yellow". If empty colors taken from _sass/ryancv/settings.scss

### Portfolio Filters Settings
portfolio:
  filters:
    - name: Properti
      slug: f-properti
    - name: Rajutan
      slug: f-rajutan
    - name: Pertanian
      slug: f-pertanian
    - name: Kuliner
      slug: f-kuliner
    - name: Galeri
      slug: f-gallery
